services:
  loop-postgres:
    image: postgres
    container_name: loop-postgres
    restart: always
    environment:
      POSTGRES_DB: ${LOOP_DB}
      POSTGRES_USER: ${LOOP_DB_USER}
      POSTGRES_PASSWORD: ${LOOP_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - loop-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: loop-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - '5050:80'
    env_file:
      - .env
    depends_on:
      - loop-postgres
volumes:
  loop-db:  
    driver: local